import type { Metadata } from "next";
import "./globals.css";
import ConfigProvider from "@/provider/ConfigProvider";
import Navbar from "@/components/custom/common/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider>{children}</ConfigProvider>
      </body>
    </html>
  );
}
